### ISSUE TITLE
add cli_tools to repo file

### ISSUE THREAD

**Issue by Karsten1987** [ros2/cli_tools#2]
+ plus tests

**Comment by Karsten1987** [comment]
I run the linters on the c++ packages. Can we run them on the python package as well?
Then, maybe starting from now, it would be a good idea to put them into the official repo files and run them on the build farm?

**Comment by mikaelarguedas** [comment]
Linters are ran automatically on both [c++](https://github.com/ros2/cli_tools/blob/master/cli_tools/CMakeLists.txt#L27) and [python](https://github.com/ros2/cli_tools/tree/master/rostopic_py/test) packages. Linter failures for [c++](https://github.com/ros2/cli_tools/pull/5/commits/52ec50747d6ea297b156c9bc967f78c54a1da329) and [python](https://github.com/ros2/cli_tools/pull/5/commits/52f80b66d19d22a0637e2bfc141570b85c666f20) have been addressed.
I think that this issue was about testing the tools behavior and not only the style. We can definitely add this repo to the ros2.repos file and come back later to add tests. But we should either keep this issue open or create another ticket to remind us to create such tests.

**Comment by gerkey** [comment]
ros2/ros2#319 adds the new repo.
